[storage]
driver = "overlay"
runroot = "/tmp/roboteam-podman-run"
graphroot = "/data/podman/storage"

[storage.options.overlay]
ignore_chown_errors = "true"
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev"
