[storage]
driver = "overlay"
runroot = "/tmp/roboteam-podman-run"
graphroot = "/var/lib/roboteam-podman/storage"
imagestore = "/data/podman/images"
transient_store = true

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
force_mask = "0700"
